version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: aa
    steps:
      # default shell is Powershell
      - run:
         command: echo hello
         shell: cmd.exe
